character = {
'Patrick':
            {'Banjo & Kazooie': 1,
             'Bayonetta': 1,
             'Bowser': 1,
             'Bowser Jr.': 1,
             'Byleth': 1,
             'Captain Falcon': 1,
             'Chrom': 1,
             'Cloud': 1,
             'Corrin': 1,
             'Daisy': 1,
             'Dark Pit': 1,
             'Dark Samus': 1,
             'Diddy Kong': 1,
             'Donkey Kong': 1,
             'Dr. Mario': 1,
             'Duck Hunt': 1,
             'Falco': 1,
             'Fox': 1,
             'Ganondorf': 1,
             'Greninja': 1,
             'Hero': 1,
             'Ice Climbers': 1,
             'Ike': 1,
             'Incineroar': 1,
             'Inkling': 1,
             'Isabelle': 1,
             'Jigglypuff': 1,
             'Joker': 1,
             'Ken': 1,
             'King Dedede': 1,
             'King K. Rool': 1,
             'Kirby': 1,
             'Link': 1,
             'Little Mac': 1,
             'Lucario': 1,
             'Lucas': 1,
             'Lucina': 1,
             'Luigi': 1,
             'Mario': 1,
             'Marth': 1,
             'Mega Man': 1,
             'Meta Knight': 1,
             'Mewtwo': 1,
             'Mii Brawler': 1,
             'Mii Gunner': 1,
             'Mii Swordfighter': 1,
             'Mr. Game & Watch': 1,
             'Ness': 1,
             'Olimar': 1,
             'Pac Man': 1,
             'Palutena': 1,
             'Peach': 1,
             'Pichu': 1,
             'Pikachu': 1,
             'Piranha Plant': 1,
             'Pit': 1,
             'Pokemon Trainer': 1,
             'Richter': 1,
             'Ridley': 1,
             'R.O.B': 1,
             'Robin': 1,
             'Rosalina and Luma': 1,
             'Roy': 1,
             'Ryu': 1,
             'Samus': 1,
             'Shiek': 1,
             'Shulk': 1,
             'Simon': 1,
             'Snake': 1,
             'Sonic': 1,
             'Terry': 1,
             'Toon Link': 1,
             'Villager': 1,
             'Wario': 1,
             'Wii Fit Trainer': 1,
             'Wolf': 1,
             'Yoshi': 1,
             'Young Link': 1,
             'Zelda': 1,
             'Zero Suit Samus': 1},
'Brad':
            {'Banjo & Kazooie': 1,
             'Bayonetta': 1,
             'Bowser': 1,
             'Bowser Jr.': 1,
             'Byleth': 1,
             'Captain Falcon': 1,
             'Chrom': 1,
             'Cloud': 1,
             'Corrin': 1,
             'Daisy': 1,
             'Dark Pit': 1,
             'Dark Samus': 1,
             'Diddy Kong': 1,
             'Donkey Kong': 1,
             'Dr. Mario': 1,
             'Duck Hunt': 1,
             'Falco': 1,
             'Fox': 1,
             'Ganondorf': 1,
             'Greninja': 1,
             'Hero': 1,
             'Ice Climbers': 1,
             'Ike': 1,
             'Incineroar': 1,
             'Inkling': 1,
             'Isabelle': 1,
             'Jigglypuff': 1,
             'Joker': 1,
             'Ken': 1,
             'King Dedede': 1,
             'King K. Rool': 1,
             'Kirby': 1,
             'Link': 1,
             'Little Mac': 1,
             'Lucario': 1,
             'Lucas': 1,
             'Lucina': 1,
             'Luigi': 1,
             'Mario': 1,
             'Marth': 1,
             'Mega Man': 1,
             'Meta Knight': 1,
             'Mewtwo': 1,
             'Mii Brawler': 1,
             'Mii Gunner': 1,
             'Mii Swordfighter': 1,
             'Mr. Game & Watch': 1,
             'Ness': 1,
             'Olimar': 1,
             'Pac Man': 1,
             'Palutena': 1,
             'Peach': 1,
             'Pichu': 1,
             'Pikachu': 1,
             'Piranha Plant': 1,
             'Pit': 1,
             'Pokemon Trainer': 1,
             'Richter': 1,
             'Ridley': 1,
             'R.O.B': 1,
             'Robin': 1,
             'Rosalina and Luma': 1,
             'Roy': 1,
             'Ryu': 1,
             'Samus': 1,
             'Shiek': 1,
             'Shulk': 1,
             'Simon': 1,
             'Snake': 1,
             'Sonic': 1,
             'Terry': 1,
             'Toon Link': 1,
             'Villager': 1,
             'Wario': 1,
             'Wii Fit Trainer': 1,
             'Wolf': 1,
             'Yoshi': 1,
             'Young Link': 1,
             'Zelda': 1,
             'Zero Suit Samus': 1},
'Simon':
            {'Banjo & Kazooie': 1,
             'Bayonetta': 1,
             'Bowser': 1,
             'Bowser Jr.': 1,
             'Byleth': 1,
             'Captain Falcon': 1,
             'Chrom': 1,
             'Cloud': 1,
             'Corrin': 1,
             'Daisy': 1,
             'Dark Pit': 1,
             'Dark Samus': 1,
             'Diddy Kong': 1,
             'Donkey Kong': 1,
             'Dr. Mario': 1,
             'Duck Hunt': 1,
             'Falco': 1,
             'Fox': 1,
             'Ganondorf': 1,
             'Greninja': 1,
             'Hero': 1,
             'Ice Climbers': 1,
             'Ike': 1,
             'Incineroar': 1,
             'Inkling': 1,
             'Isabelle': 1,
             'Jigglypuff': 1,
             'Joker': 1,
             'Ken': 1,
             'King Dedede': 1,
             'King K. Rool': 1,
             'Kirby': 1,
             'Link': 1,
             'Little Mac': 1,
             'Lucario': 1,
             'Lucas': 1,
             'Lucina': 1,
             'Luigi': 1,
             'Mario': 1,
             'Marth': 1,
             'Mega Man': 1,
             'Meta Knight': 1,
             'Mewtwo': 1,
             'Mii Brawler': 1,
             'Mii Gunner': 1,
             'Mii Swordfighter': 1,
             'Mr. Game & Watch': 1,
             'Ness': 1,
             'Olimar': 1,
             'Pac Man': 1,
             'Palutena': 1,
             'Peach': 1,
             'Pichu': 1,
             'Pikachu': 1,
             'Piranha Plant': 1,
             'Pit': 1,
             'Pokemon Trainer': 1,
             'Richter': 1,
             'Ridley': 1,
             'R.O.B': 1,
             'Robin': 1,
             'Rosalina and Luma': 1,
             'Roy': 1,
             'Ryu': 1,
             'Samus': 1,
             'Shiek': 1,
             'Shulk': 1,
             'Simon': 1,
             'Snake': 1,
             'Sonic': 1,
             'Terry': 1,
             'Toon Link': 1,
             'Villager': 1,
             'Wario': 1,
             'Wii Fit Trainer': 1,
             'Wolf': 1,
             'Yoshi': 1,
             'Young Link': 1,
             'Zelda': 1,
             'Zero Suit Samus': 1},
'Joey':
            {'Banjo & Kazooie': 1,
             'Bayonetta': 1,
             'Bowser': 1,
             'Bowser Jr.': 1,
             'Byleth': 1,
             'Captain Falcon': 1,
             'Chrom': 1,
             'Cloud': 1,
             'Corrin': 1,
             'Daisy': 1,
             'Dark Pit': 1,
             'Dark Samus': 1,
             'Diddy Kong': 1,
             'Donkey Kong': 1,
             'Dr. Mario': 1,
             'Duck Hunt': 1,
             'Falco': 1,
             'Fox': 1,
             'Ganondorf': 1,
             'Greninja': 1,
             'Hero': 1,
             'Ice Climbers': 1,
             'Ike': 1,
             'Incineroar': 1,
             'Inkling': 1,
             'Isabelle': 1,
             'Jigglypuff': 1,
             'Joker': 1,
             'Ken': 1,
             'King Dedede': 1,
             'King K. Rool': 1,
             'Kirby': 1,
             'Link': 1,
             'Little Mac': 1,
             'Lucario': 1,
             'Lucas': 1,
             'Lucina': 1,
             'Luigi': 1,
             'Mario': 1,
             'Marth': 1,
             'Mega Man': 1,
             'Meta Knight': 1,
             'Mewtwo': 1,
             'Mii Brawler': 1,
             'Mii Gunner': 1,
             'Mii Swordfighter': 1,
             'Mr. Game & Watch': 1,
             'Ness': 1,
             'Olimar': 1,
             'Pac Man': 1,
             'Palutena': 1,
             'Peach': 1,
             'Pichu': 1,
             'Pikachu': 1,
             'Piranha Plant': 1,
             'Pit': 1,
             'Pokemon Trainer': 1,
             'Richter': 1,
             'Ridley': 1,
             'R.O.B': 1,
             'Robin': 1,
             'Rosalina and Luma': 1,
             'Roy': 1,
             'Ryu': 1,
             'Samus': 1,
             'Shiek': 1,
             'Shulk': 1,
             'Simon': 1,
             'Snake': 1,
             'Sonic': 1,
             'Terry': 1,
             'Toon Link': 1,
             'Villager': 1,
             'Wario': 1,
             'Wii Fit Trainer': 1,
             'Wolf': 1,
             'Yoshi': 1,
             'Young Link': 1,
             'Zelda': 1,
             'Zero Suit Samus': 1}
             }

# player = input('player?(Patrick, Brad, Simon, Joey')
# weighted_list = []
#
# for c in character[player]:
#     for w in range(character[player][c]):
#         weighted_list.append(c)
# print(random.choice(weighted_list))
